from pathlib import Path
base=Path('/tmp/pjm/app/templates/admin')
files={
'content_form.html':'''{% extends 'base.html' %}
{% block title %}{{ 'Editar' if content else 'Adicionar' }} material · Portal Python{% endblock %}
{% block content %}
<section class="admin-shell workspace-shell">
  <div class="workspace-head">
    <div><a class="back-link" href="{{url_for('admin.dashboard')}}">← Painel do professor</a><span class="eyebrow">PUBLICAÇÃO</span><h1>{{'Editar material' if content else 'Adicionar material'}}</h1><p>Preencha as informações abaixo. Os campos estão separados por etapas para facilitar a publicação.</p></div>
    <div class="workspace-head-badge">📚 <span>Material</span></div>
  </div>
  <form class="publisher workspace-form" method="post" enctype="multipart/form-data">
    <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
    <div class="workspace-columns">
      <div class="workspace-main">
        <div class="publisher-card form-section">
          <div class="form-section-head"><div class="step-number">1</div><div><span class="eyebrow">INFORMAÇÕES</span><h2>Dados do material</h2><p>Defina o título, série, matéria e tipo.</p></div></div>
          <div class="form-grid tidy-grid">
            <label class="field-block full">Título<input name="title" value="{{content.title if content else ''}}" placeholder="Ex.: Ligações Pythons" required></label>
            <label class="field-block">Série<select name="series_id" required>{% for s in series %}<option value="{{s.id}}" {% if content and content.series_id==s.id %}selected{% endif %}>{{s.name}}</option>{% endfor %}</select></label>
            <label class="field-block">Matéria<select name="subject_id" required>{% for s in subjects %}<option value="{{s.id}}" {% if content and content.subject_id==s.id %}selected{% endif %}>{{s.series.name}} · {{s.name}}</option>{% endfor %}</select></label>
            <label class="field-block full">Tipo de material<select name="kind" required>{% for value,label in [('file','Arquivo'),('pdf','PDF'),('slide','Slides'),('video','Vídeo'),('link','Link externo'),('explanation','Explicação')] %}<option value="{{value}}" {% if content and content.kind==value %}selected{% endif %}>{{label}}</option>{% endfor %}</select></label>
            <label class="field-block full">Descrição<textarea name="description" placeholder="Explique rapidamente o que o aluno encontrará neste material.">{{content.description if content else ''}}</textarea></label>
          </div>
        </div>
        <div class="publisher-card form-section">
          <div class="form-section-head"><div class="step-number">2</div><div><span class="eyebrow">ARQUIVO / LINK</span><h2>Fonte do material</h2><p>Envie um arquivo ou informe um endereço externo.</p></div></div>
          <div class="field-block"><label>Arquivo do dispositivo<input class="file-input" name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.gif,.ppt,.pptx,.doc,.docx,.txt"></label></div>
          {% if content and content.file_name %}<div class="source-note">📎 Arquivo atual: <strong>{{content.file_name.split("-")[-1] if content.file_name else ""}}</strong><br><span>Sem novo envio, o arquivo atual será mantido.</span></div>{% endif %}
          <div class="field-block"><label>Link externo / Google Drive / vídeo<input name="external_url" type="url" value="{{content.external_url if content else ''}}" placeholder="https://..."></label></div>
          <a class="btn secondary compact-btn" href="https://drive.google.com/drive/my-drive" target="_blank" rel="noopener noreferrer">↗ Abrir Google Drive</a>
        </div>
        <div class="publisher-card form-section">
          <div class="form-section-head"><div class="step-number">3</div><div><span class="eyebrow">EXPLICAÇÃO</span><h2>Texto complementar</h2><p>Use este espaço quando o material for uma explicação.</p></div></div>
          <label class="field-block">Conteúdo<textarea name="body" rows="12" placeholder="Escreva a explicação que será apresentada aos alunos.">{{content.body if content else ''}}</textarea></label>
        </div>
      </div>
      <aside class="workspace-side">
        <div class="publish-summary"><span class="summary-icon">✓</span><h3>Pronto para publicar?</h3><p>Revise os dados antes de salvar. Você poderá editar o material depois.</p><button class="btn admin-primary publish-btn" type="submit">💾 {{'Salvar alterações' if content else 'Publicar material'}}</button></div>
        <div class="workspace-help"><strong>💡 Dica</strong><p>Use títulos curtos e uma descrição objetiva. Links do Drive, YouTube e outros serviços podem ser usados.</p></div>
      </aside>
    </div>
  </form>
</section>
{% endblock %}''',
'contents.html':'''{% extends 'base.html' %}{% block title %}Materiais · Portal Python{% endblock %}{% block content %}
<section class="admin-shell workspace-shell">
  <div class="workspace-head"><div><span class="eyebrow">BIBLIOTECA</span><h1>Meus materiais</h1><p>Encontre, abra, edite ou exclua tudo o que já foi publicado.</p></div><a class="btn admin-primary" href="{{url_for('admin.content_new')}}">＋ Adicionar material</a></div>
  <div class="library-toolbar"><div><strong>{{ contents|length }}</strong><span>material(is) publicado(s)</span></div><div class="library-hint">📦 Biblioteca do professor</div></div>
  <div class="material-list organized-list">{% for c in contents %}
    <article class="material-row organized-material">
      <div class="material-icon large-icon">{{ {'file':'📎','pdf':'📄','slide':'📊','video':'🎬','link':'🔗','explanation':'✍️'}[c.kind] }}</div>
      <div class="material-main"><div class="material-meta"><span class="badge">{{c.series.name}}</span><span class="badge subtle-badge">{{c.subject.name}}</span><span class="type-label">{{ {'file':'Arquivo','pdf':'PDF','slide':'Slides','video':'Vídeo','link':'Link','explanation':'Explicação'}[c.kind] }}</span></div><h3>{{c.title}}</h3><p>{{c.description or 'Material de estudo publicado no Portal Python.'}}</p></div>
      <div class="material-actions organized-actions"><a class="btn secondary" href="{{url_for('admin.content_edit',id=c.id)}}">✏️ Editar</a>{% if c.kind in ['file','pdf'] and c.file_name %}<a class="btn secondary" href="{{url_for('admin.file',filename=c.file_name)}}" target="_blank">↗ Abrir</a>{% elif c.external_url %}<a class="btn secondary" href="{{c.external_url}}" target="_blank" rel="noopener noreferrer">↗ Abrir</a>{% endif %}<form method="post" action="{{url_for('admin.content_delete',id=c.id)}}"><input type="hidden" name="csrf_token" value="{{csrf_token()}}"><button class="btn danger" type="submit">🗑 Excluir</button></form></div>
    </article>
  {% else %}<div class="publisher-card empty-state"><span>📦</span><h2>Nenhum material ainda</h2><p>Publique seu primeiro material para começar.</p><a class="btn admin-primary" href="{{url_for('admin.content_new')}}">＋ Adicionar material</a></div>{% endfor %}</div>
</section>{% endblock %}''',
'users.html':'''{% extends 'base.html' %}{% block title %}Usuários · Portal Python{% endblock %}{% block content %}
<section class="admin-shell workspace-shell"><div class="workspace-head"><div><span class="eyebrow">CONTAS</span><h1>Usuários</h1><p>Gerencie as contas dos alunos com uma visualização simples e organizada.</p></div><div class="workspace-head-badge">👥 <span>{{ users|length }} conta(s)</span></div></div>
<div class="library-toolbar"><div><strong>{{ users|length }}</strong><span>usuário(s) cadastrado(s)</span></div><div class="library-hint">🔐 Conta de professor protegida</div></div>
<div class="user-list">{% for u in users %}<article class="user-row"><div class="user-avatar">{{'👨‍🏫' if u.is_admin else '🎓'}}</div><div class="user-main"><div class="user-name-line"><h3>{{u.name}}</h3><span class="role-badge {{'admin-role' if u.is_admin else 'student-role'}}">{{'ADMINISTRADOR' if u.is_admin else 'ALUNO'}}</span></div><p>{{u.email}}</p></div><div class="user-action">{% if not u.is_admin %}<form method="post" action="{{url_for('admin.user_delete',id=u.id)}}"><input type="hidden" name="csrf_token" value="{{csrf_token()}}"><button class="btn danger" type="submit">🗑 Excluir</button></form>{% else %}<span class="protected-label">🔒 Protegido</span>{% endif %}</div></article>{% else %}<div class="publisher-card empty-state"><span>👥</span><h2>Nenhum usuário</h2><p>Ainda não existem contas cadastradas.</p></div>{% endfor %}</div></section>{% endblock %}''',
'activities.html':'''{% extends 'base.html' %}{% block title %}Atividades · Portal Python{% endblock %}{% block content %}<section class="admin-shell workspace-shell"><div class="workspace-head"><div><span class="eyebrow">AVALIAÇÃO</span><h1>Atividades</h1><p>Crie atividades e gerencie questões com correção automática.</p></div></div><form class="publisher-card form-section" method="post"><div class="form-section-head"><div class="step-number">1</div><div><span class="eyebrow">NOVA ATIVIDADE</span><h2>Dados da atividade</h2><p>Informe os dados básicos antes de criar as questões.</p></div></div><div class="form-grid tidy-grid"><label class="field-block full">Título<input name="title" placeholder="Ex.: Revisão de ligações Pythons" required></label><label class="field-block">Série<select name="series_id" required>{% for s in series %}<option value="{{s.id}}">{{s.name}}</option>{% endfor %}</select></label><label class="field-block">Matéria<select name="subject_id" required>{% for s in series %}{% for sub in s.subjects %}<option value="{{sub.id}}">{{s.name}} · {{sub.name}}</option>{% endfor %}{% endfor %}</select></label><label class="field-block full">Descrição<textarea name="description" placeholder="Explique o objetivo da atividade."></textarea></label></div><button class="btn admin-primary" type="submit">＋ Criar atividade</button></form><div class="material-list organized-list">{% for a in activities %}<article class="material-row organized-material"><div class="material-icon large-icon">📝</div><div class="material-main"><div class="material-meta"><span class="badge">{{a.series.name}}</span><span class="badge subtle-badge">{{a.subject.name}}</span></div><h3>{{a.title}}</h3><p>{{a.get_questions()|length}} questão(ões)</p></div><div class="material-actions organized-actions"><a class="btn secondary" href="{{url_for('admin.activity_edit',id=a.id)}}">✏️ Editar</a><form method="post" action="{{url_for('admin.activity_delete',id=a.id)}}"><input type="hidden" name="csrf_token" value="{{csrf_token()}}"><button class="btn danger" type="submit">🗑 Excluir</button></form></div></article>{% else %}<div class="publisher-card empty-state"><span>📝</span><h2>Nenhuma atividade</h2><p>Crie a primeira atividade para seus alunos.</p></div>{% endfor %}</div></section>{% endblock %}''',
'experiments.html':'''{% extends 'base.html' %}{% block title %}Projetos Python · Portal Python{% endblock %}{% block content %}<section class="admin-shell workspace-shell"><div class="workspace-head"><div><span class="eyebrow">PROJETO PYTHON</span><h1>Projetos Python</h1><p>Cadastre experiências com objetivo, materiais, etapas e segurança.</p></div></div><form method="post" class="publisher-card form-section"><div class="form-section-head"><div class="step-number">1</div><div><span class="eyebrow">NOVO EXPERIMENTO</span><h2>Informações do laboratório</h2><p>Organize cada parte do roteiro em campos separados.</p></div></div><div class="form-grid tidy-grid"><label class="field-block full">Título<input name="title" placeholder="Ex.: Reação ácido-base" required></label><label class="field-block">Série<select name="series_id" required>{% for s in series %}<option value="{{s.id}}">{{s.name}}</option>{% endfor %}</select></label><label class="field-block">Matéria<select name="subject_id" required>{% for s in series %}{% for sub in s.subjects %}<option value="{{sub.id}}">{{s.name}} · {{sub.name}}</option>{% endfor %}{% endfor %}</select></label>{% for f,l in [('objective','Objetivo'),('materials','Materiais'),('steps','Passo a passo'),('safety','Segurança'),('conclusion','Conclusão')] %}<label class="field-block">{{l}}<textarea name="{{f}}" placeholder="{{l}} do experimento"></textarea></label>{% endfor %}</div><button class="btn admin-primary" type="submit">🧪 Publicar experimento</button></form><div class="material-list organized-list">{% for e in experiments %}<article class="material-row organized-material"><div class="material-icon large-icon">🧪</div><div class="material-main"><div class="material-meta"><span class="badge">{{e.series.name}}</span><span class="badge subtle-badge">{{e.subject.name}}</span></div><h3>{{e.title}}</h3><p>{{e.description or e.objective or 'Experimento de Python'}}</p></div><div class="material-actions organized-actions"><a class="btn secondary" href="{{url_for('admin.experiment_edit',id=e.id)}}">✏️ Editar</a><form method="post" action="{{url_for('admin.experiment_delete',id=e.id)}}"><input type="hidden" name="csrf_token" value="{{csrf_token()}}"><button class="btn danger" type="submit">🗑 Excluir</button></form></div></article>{% else %}<div class="publisher-card empty-state"><span>🧪</span><h2>Nenhum experimento</h2><p>Cadastre seu primeiro roteiro de laboratório.</p></div>{% endfor %}</div></section>{% endblock %}''',
'subjects.html':'''{% extends 'base.html' %}{% block title %}Matérias · Portal Python{% endblock %}{% block content %}<section class="admin-shell workspace-shell"><div class="workspace-head"><div><span class="eyebrow">ORGANIZAÇÃO</span><h1>Matérias</h1><p>Crie e organize as matérias de cada série.</p></div></div><form class="publisher-card form-section compact-section" method="post"><div class="form-section-head"><div class="step-number">＋</div><div><h2>Nova matéria</h2><p>Escolha a série e informe o nome da matéria.</p></div></div><div class="inline-create"><input name="name" placeholder="Nome da matéria" required><select name="series_id" required><option value="">Série...</option>{% for s in series %}<option value="{{s.id}}">{{s.name}}</option>{% endfor %}</select><button class="btn admin-primary">Criar matéria</button></div></form><div class="manage-grid">{% for s in subjects %}<article class="manage-card"><div class="manage-icon">🧪</div><div class="manage-content"><span class="badge">{{s.series.name}}</span><h2>{{s.name}}</h2></div><div class="manage-actions"><a class="btn secondary" href="{{url_for('admin.subject_edit',id=s.id)}}">✏️ Editar</a><form method="post" action="{{url_for('admin.subject_delete',id=s.id)}}"><input type="hidden" name="csrf_token" value="{{csrf_token()}}"><button class="btn danger">🗑 Excluir</button></form></div></article>{% else %}<div class="publisher-card empty-state"><span>🧪</span><h2>Nenhuma matéria</h2></div>{% endfor %}</div></section>{% endblock %}''',
'series.html':'''{% extends 'base.html' %}{% block title %}Séries · Portal Python{% endblock %}{% block content %}<section class="admin-shell workspace-shell"><div class="workspace-head"><div><span class="eyebrow">ORGANIZAÇÃO</span><h1>Séries</h1><p>Configure as séries e mantenha a estrutura das turmas organizada.</p></div></div><form class="publisher-card form-section compact-section" method="post"><div class="form-section-head"><div class="step-number">＋</div><div><h2>Nova série</h2><p>Adicione uma série ao portal.</p></div></div><div class="inline-create"><input name="name" placeholder="Ex.: 4º ano" required><button class="btn admin-primary">Criar série</button></div></form><div class="manage-grid">{% for s in series %}<article class="manage-card"><div class="manage-icon">🎓</div><div class="manage-content"><h2>{{s.name}}</h2><p class="muted">Série do Portal Python</p></div><div class="manage-actions"><a class="btn secondary" href="{{url_for('admin.series_edit',id=s.id)}}">✏️ Editar</a><form method="post" action="{{url_for('admin.series_delete',id=s.id)}}"><input type="hidden" name="csrf_token" value="{{csrf_token()}}"><button class="btn danger">🗑 Excluir</button></form></div></article>{% else %}<div class="publisher-card empty-state"><span>🎓</span><h2>Nenhuma série</h2></div>{% endfor %}</div></section>{% endblock %}''',
'edit_simple.html':'''{% extends 'base.html' %}{% block title %}{{title}} · Portal Python{% endblock %}{% block content %}<section class="admin-shell workspace-shell narrow-workspace"><a class="back-link" href="javascript:history.back()">← Voltar</a><div class="workspace-head"><div><span class="eyebrow">EDIÇÃO</span><h1>{{title}}</h1><p>Atualize a informação e salve quando terminar.</p></div></div><div class="publisher-card form-section"><form method="post"><input type="hidden" name="csrf_token" value="{{csrf_token()}}"><label class="field-block">Nome<input name="name" value="{{value}}" required></label><button class="btn admin-primary">💾 Salvar</button></form></div></section>{% endblock %}''',
'subject_edit.html':'''{% extends 'base.html' %}{% block title %}Editar matéria · Portal Python{% endblock %}{% block content %}<section class="admin-shell workspace-shell narrow-workspace"><a class="back-link" href="{{url_for('admin.subjects_list')}}">← Matérias</a><div class="workspace-head"><div><span class="eyebrow">EDIÇÃO</span><h1>Editar matéria</h1><p>Atualize o nome e a série da matéria.</p></div></div><div class="publisher-card form-section"><form method="post" class="form-grid"><input type="hidden" name="csrf_token" value="{{csrf_token()}}"><label class="field-block">Nome<input name="name" value="{{subject.name}}" required></label><label class="field-block">Série<select name="series_id" required>{% for s in series %}<option value="{{s.id}}" {% if s.id==subject.series_id %}selected{% endif %}>{{s.name}}</option>{% endfor %}</select></label><div class="full"><button class="btn admin-primary">💾 Salvar alterações</button></div></form></div></section>{% endblock %}''',
'settings.html':'''{% extends 'base.html' %}{% block title %}Configurações · Portal Python{% endblock %}{% block content %}<section class="admin-shell workspace-shell narrow-workspace"><div class="workspace-head"><div><span class="eyebrow">SISTEMA</span><h1>Configurações</h1><p>Orientações para manter o Portal Python seguro e pronto para produção.</p></div></div><div class="settings-grid"><div class="publisher-card settings-card"><span>🔐</span><h2>Segurança</h2><p>Configurações sensíveis ficam nas variáveis de ambiente. O cadastro público não pode promover um aluno a administrador.</p></div><div class="publisher-card settings-card"><span>⚙️</span><h2>Produção</h2><p>Para produção, configure HTTPS, SECRET_KEY, PostgreSQL e armazenamento persistente para PDFs.</p></div></div></section>{% endblock %}''',
}
for name,text in files.items(): (base/name).write_text(text)
