"""Atividades prontas de Python para uso pelo professor.

O conteúdo segue o módulo de Laços de Repetição enviado para o Portal Python:
conceito de laço, for, indentação, while, loop infinito, break/continue,
comparação for x while e exercícios com range/acumulador.
"""

PREBUILT_ACTIVITIES = [
    {
        "slug": "fundamentos-lacos-facil",
        "title": "Laços de Repetição — Fundamentos",
        "description": "Revisão inicial: o que é um laço, para que serve e quais são os dois tipos trabalhados no módulo.",
        "difficulty": "facil",
        "questions": [
            {"question": "O que é um laço de repetição?", "options": ["Um bloco executado várias vezes sem reescrever o código", "Um comando que apaga o programa", "Uma forma de criar apenas uma variável", "Um tipo de comentário"], "correct": "Um bloco executado várias vezes sem reescrever o código"},
            {"question": "Qual é a principal vantagem dos laços de repetição?", "options": ["Evitar repetição manual de código", "Eliminar a indentação", "Impedir que o programa execute", "Transformar Python em outra linguagem"], "correct": "Evitar repetição manual de código"},
            {"question": "Quais dois tipos de laço são apresentados no módulo?", "options": ["for e while", "if e else", "try e except", "def e return"], "correct": "for e while"},
            {"question": "O for é indicado especialmente para percorrer o quê?", "options": ["Sequências como listas, strings e range()", "Somente arquivos", "Somente números negativos", "Apenas condições verdadeiras"], "correct": "Sequências como listas, strings e range()"},
        ],
    },
    {
        "slug": "for-pratica-facil",
        "title": "Laço FOR — Primeiros passos",
        "description": "Pratique a sintaxe do for e a utilização de range() com exemplos simples.",
        "difficulty": "facil",
        "questions": [
            {"question": "Qual sintaxe representa corretamente um laço for?", "options": ["for variável in sequência:", "for variável = sequência", "repeat variável in sequência", "while variável in sequência"], "correct": "for variável in sequência:"},
            {"question": "Qual é a saída de `for i in range(3): print(i)`?", "options": ["0, 1, 2", "1, 2, 3", "0, 1, 2, 3", "3, 2, 1"], "correct": "0, 1, 2"},
            {"question": "Em Python, o bloco dentro do for precisa de quê?", "options": ["Indentação", "Um ponto e vírgula no final", "Uma segunda condição", "Um arquivo externo"], "correct": "Indentação"},
            {"question": "Em `range(0, 11, 2)`, qual é o objetivo do 2?", "options": ["Definir o passo da sequência", "Definir o número de alternativas", "Parar o programa", "Indicar a indentação"], "correct": "Definir o passo da sequência"},
        ],
    },
    {
        "slug": "while-pratica-facil",
        "title": "Laço WHILE — Condições",
        "description": "Identifique quando usar while e reconheça uma condição de parada clara.",
        "difficulty": "facil",
        "questions": [
            {"question": "Quando o while é especialmente útil?", "options": ["Quando uma condição determina o fim da repetição", "Somente quando há uma lista", "Somente para imprimir texto uma vez", "Apenas para definir funções"], "correct": "Quando uma condição determina o fim da repetição"},
            {"question": "Qual código atualiza corretamente a variável de controle?", "options": ["i = 0; while i < 3: i += 1", "i = 0; while i < 3: pass", "i = 0; while i < 3: i = 0", "i = 0; while i < 3: break sempre"], "correct": "i = 0; while i < 3: i += 1"},
            {"question": "O que deve existir para o while conseguir terminar normalmente?", "options": ["Uma condição de parada que possa se tornar falsa", "Uma lista obrigatoriamente", "Um print em cada linha", "Um for dentro dele"], "correct": "Uma condição de parada que possa se tornar falsa"},
            {"question": "Qual é a sequência produzida por `i=0; while i<3: print(i); i+=1`?", "options": ["0, 1, 2", "1, 2, 3", "0, 1, 2, 3", "Somente 3"], "correct": "0, 1, 2"},
        ],
    },
    {
        "slug": "indentacao-loop-medio",
        "title": "FOR e Indentação — Erros comuns",
        "description": "Treine a identificação e a correção do erro de indentação dentro de um laço for.",
        "difficulty": "medio",
        "questions": [
            {"question": "O que acontece com este código? `for i in range(3):` seguido de `print(i)` sem recuo?", "options": ["Pode ocorrer IndentationError", "Sempre imprime 0, 1 e 2", "Cria automaticamente a indentação", "Vira um while"], "correct": "Pode ocorrer IndentationError"},
            {"question": "Qual é a correção apresentada no módulo?", "options": ["Recuar `print(i)` para dentro do bloco do for", "Remover o for", "Trocar print por input", "Colocar tudo na mesma linha sem dois-pontos"], "correct": "Recuar `print(i)` para dentro do bloco do for"},
            {"question": "Por que a indentação é importante em Python?", "options": ["Ela define a estrutura do bloco do laço", "Ela muda o nome das variáveis", "Ela substitui todas as condições", "Ela serve apenas para deixar o código bonito"], "correct": "Ela define a estrutura do bloco do laço"},
            {"question": "Qual versão está corretamente indentada?", "options": ["for i in range(3):\n    print(i)", "for i in range(3):\nprint(i)", "for i range(3):\n print(i)", "for i = range(3):\nprint(i)"], "correct": "for i in range(3):\n    print(i)"},
        ],
    },
    {
        "slug": "while-loop-infinito-medio",
        "title": "WHILE — Evitando Loop Infinito",
        "description": "Analise a variável de controle e encontre o motivo de um while não terminar.",
        "difficulty": "medio",
        "questions": [
            {"question": "Por que `i = 0; while i < 3: print(i)` pode rodar para sempre?", "options": ["Porque i nunca é atualizado", "Porque o print está dentro do laço", "Porque 3 é um número ímpar", "Porque while não aceita números"], "correct": "Porque i nunca é atualizado"},
            {"question": "Qual linha corrige o problema do loop infinito mostrado no módulo?", "options": ["i += 1", "i -= 1", "print(i)", "while i < 3"], "correct": "i += 1"},
            {"question": "Se a condição é `i < 3`, o que acontece quando i chega a 3?", "options": ["A condição fica falsa e o laço termina", "O laço reinicia automaticamente", "i volta para 0", "O programa cria outro while"], "correct": "A condição fica falsa e o laço termina"},
            {"question": "Qual cuidado é destacado para usar while?", "options": ["Ter uma condição de parada clara e atualizar a variável", "Nunca atualizar variáveis", "Usar sempre range()", "Evitar indentação"], "correct": "Ter uma condição de parada clara e atualizar a variável"},
        ],
    },
    {
        "slug": "break-continue-medio",
        "title": "BREAK e CONTINUE — Controle de fluxo",
        "description": "Entenda como break encerra o laço e como continue pula uma iteração.",
        "difficulty": "medio",
        "questions": [
            {"question": "O que `break` faz dentro de um laço?", "options": ["Sai do laço", "Pula apenas a iteração atual e continua", "Repete o laço para sempre", "Cria uma nova variável"], "correct": "Sai do laço"},
            {"question": "O que `continue` faz dentro de um laço?", "options": ["Pula a iteração atual", "Encerra todo o programa", "Apaga a variável de controle", "Transforma for em while"], "correct": "Pula a iteração atual"},
            {"question": "No exemplo `for i in range(5)` com `if i == 3: break`, quais valores são impressos?", "options": ["0, 1, 2", "0, 1, 2, 3", "1, 2, 3, 4", "0, 2, 4"], "correct": "0, 1, 2"},
            {"question": "No exemplo com continue quando `i == 1`, quais valores são impressos?", "options": ["0, 2", "0, 1, 2", "1", "2"], "correct": "0, 2"},
        ],
    },
    {
        "slug": "for-vs-while-dificil",
        "title": "FOR x WHILE — Escolha do laço",
        "description": "Compare os dois tipos de laço e escolha a estrutura adequada para cada situação apresentada no módulo.",
        "difficulty": "dificil",
        "questions": [
            {"question": "Qual combinação está correta?", "options": ["FOR → sequências conhecidas; WHILE → condições dinâmicas", "FOR → somente condições; WHILE → somente listas", "FOR → encerra laços; WHILE → pula iterações", "FOR → funções; WHILE → classes"], "correct": "FOR → sequências conhecidas; WHILE → condições dinâmicas"},
            {"question": "Qual laço é mais alinhado ao exemplo de percorrer `range(3)`?", "options": ["for", "while obrigatoriamente", "if", "break"], "correct": "for"},
            {"question": "Qual laço é apresentado como apropriado quando o fim é determinado por uma condição?", "options": ["while", "for", "continue", "range"], "correct": "while"},
            {"question": "O que for e while têm em comum segundo o resumo do módulo?", "options": ["Ambos controlam iteração e podem usar break/continue", "Ambos exigem listas", "Ambos são funções", "Ambos dispensam indentação"], "correct": "Ambos controlam iteração e podem usar break/continue"},
        ],
    },
    {
        "slug": "numeros-pares-dificil",
        "title": "Desafio — Números pares de 0 a 10",
        "description": "Resolva o exercício do módulo usando for e depois compare com a solução em while.",
        "difficulty": "dificil",
        "questions": [
            {"question": "Qual for imprime os números pares de 0 a 10?", "options": ["for n in range(0, 11, 2): print(n)", "for n in range(1, 10, 2): print(n)", "for n in range(0, 10, 1): print(n)", "for n in range(2, 11, 3): print(n)"], "correct": "for n in range(0, 11, 2): print(n)"},
            {"question": "Qual sequência deve aparecer no exercício de números pares?", "options": ["0, 2, 4, 6, 8, 10", "1, 3, 5, 7, 9", "0, 1, 2, 3, 4, 5", "2, 4, 6, 8"], "correct": "0, 2, 4, 6, 8, 10"},
            {"question": "No while do exercício, qual atualização mantém o passo de 2?", "options": ["n += 2", "n += 1", "n -= 2", "n = 2"], "correct": "n += 2"},
            {"question": "Qual condição aparece no while para chegar até 10?", "options": ["n <= 10", "n < 0", "n == 10 desde o início", "n > 10"], "correct": "n <= 10"},
        ],
    },
    {
        "slug": "desafio-acumulador-dificil",
        "title": "Desafio — Acumulando valores",
        "description": "Aplique a ideia de repetição para resolver o desafio final do módulo: acumular valores de 1 a 100.",
        "difficulty": "dificil",
        "questions": [
            {"question": "Qual é a ideia central do desafio de somar os números de 1 a 100?", "options": ["Usar um laço e acumular os valores em uma variável total", "Usar somente print sem variável", "Usar apenas break", "Evitar qualquer repetição"], "correct": "Usar um laço e acumular os valores em uma variável total"},
            {"question": "Qual nome de variável é sugerido pela dica do módulo para guardar a soma?", "options": ["total", "break", "range", "while"], "correct": "total"},
            {"question": "Qual estrutura pode ser usada para percorrer os valores de 1 a 100?", "options": ["Um laço de repetição", "Somente uma condição if", "Apenas continue", "Somente um comentário"], "correct": "Um laço de repetição"},
            {"question": "O desafio de 1 a 100 aparece em qual momento do módulo?", "options": ["Depois do exercício de for e while com números pares", "Antes de explicar o que é um laço", "Na parte sobre login", "No visualizador de PowerPoint"], "correct": "Depois do exercício de for e while com números pares"},
        ],
    },
]


# Lote adicional: 50 atividades prontas sobre Laços de Repetição.
# Mantém o mesmo formato de dados usado pela biblioteca original.
_ADDITIONAL = [
    {'slug': 'laços-repeticao-extra-01', 'title': 'Laços de Repetição — Atividade Extra 01', 'description': 'Atividade pronta de nível facil, revisando conceito de laço conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de conceito de laço, qual alternativa está correta?', 'options': ['Executa um bloco várias vezes sem reescrever o código', 'Repetição de um bloco de código', 'Evitar repetição manual de código', 'for e while'], 'correct': 'Executa um bloco várias vezes sem reescrever o código'}, {'question': 'Qual item corresponde ao conceito principal de conceito de laço?', 'options': ['Repetição de um bloco de código', 'Evitar repetição manual de código', 'Executa um bloco várias vezes sem reescrever o código', 'for e while'], 'correct': 'Repetição de um bloco de código'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre conceito de laço?', 'options': ['for e while', 'Repetição de um bloco de código', 'Executa um bloco várias vezes sem reescrever o código', 'Evitar repetição manual de código'], 'correct': 'for e while'}, {'question': 'Qual afirmação resume corretamente conceito de laço?', 'options': ['Evitar repetição manual de código', 'Executa um bloco várias vezes sem reescrever o código', 'for e while', 'Repetição de um bloco de código'], 'correct': 'Evitar repetição manual de código'}]},
    {'slug': 'laços-repeticao-extra-02', 'title': 'Laços de Repetição — Atividade Extra 02', 'description': 'Atividade pronta de nível facil, revisando conceito de laço conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de conceito de laço, qual alternativa está correta?', 'options': ['Percorrer sequências como listas, strings e range()', 'for', 'while', 'Quando uma condição determina o fim'], 'correct': 'Percorrer sequências como listas, strings e range()'}, {'question': 'Qual item corresponde ao conceito principal de conceito de laço?', 'options': ['for', 'while', 'Percorrer sequências como listas, strings e range()', 'Quando uma condição determina o fim'], 'correct': 'for'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre conceito de laço?', 'options': ['Quando uma condição determina o fim', 'for', 'Percorrer sequências como listas, strings e range()', 'while'], 'correct': 'Quando uma condição determina o fim'}, {'question': 'Qual afirmação resume corretamente conceito de laço?', 'options': ['while', 'Percorrer sequências como listas, strings e range()', 'Quando uma condição determina o fim', 'for'], 'correct': 'while'}]},
    {'slug': 'laços-repeticao-extra-03', 'title': 'Laços de Repetição — Atividade Extra 03', 'description': 'Atividade pronta de nível facil, revisando for e range conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de for e range, qual alternativa está correta?', 'options': ['0, 1, 2', 'range(3)', 'range(0, 11, 2)', 'Usar 2 como passo'], 'correct': '0, 1, 2'}, {'question': 'Qual item corresponde ao conceito principal de for e range?', 'options': ['range(3)', 'range(0, 11, 2)', '0, 1, 2', 'Usar 2 como passo'], 'correct': 'range(3)'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre for e range?', 'options': ['Usar 2 como passo', 'range(3)', '0, 1, 2', 'range(0, 11, 2)'], 'correct': 'Usar 2 como passo'}, {'question': 'Qual afirmação resume corretamente for e range?', 'options': ['range(0, 11, 2)', '0, 1, 2', 'Usar 2 como passo', 'range(3)'], 'correct': 'range(0, 11, 2)'}]},
    {'slug': 'laços-repeticao-extra-04', 'title': 'Laços de Repetição — Atividade Extra 04', 'description': 'Atividade pronta de nível facil, revisando for e indentação conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de for e indentação, qual alternativa está correta?', 'options': ['Define o bloco do laço', 'Indentação', 'IndentationError', 'Falta de recuo no bloco'], 'correct': 'Define o bloco do laço'}, {'question': 'Qual item corresponde ao conceito principal de for e indentação?', 'options': ['Indentação', 'IndentationError', 'Define o bloco do laço', 'Falta de recuo no bloco'], 'correct': 'Indentação'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre for e indentação?', 'options': ['Falta de recuo no bloco', 'Indentação', 'Define o bloco do laço', 'IndentationError'], 'correct': 'Falta de recuo no bloco'}, {'question': 'Qual afirmação resume corretamente for e indentação?', 'options': ['IndentationError', 'Define o bloco do laço', 'Falta de recuo no bloco', 'Indentação'], 'correct': 'IndentationError'}]},
    {'slug': 'laços-repeticao-extra-05', 'title': 'Laços de Repetição — Atividade Extra 05', 'description': 'Atividade pronta de nível facil, revisando while conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de while, qual alternativa está correta?', 'options': ['Pode tornar-se falsa', 'Condição de parada', 'i += 1', 'Atualizar a variável de controle'], 'correct': 'Pode tornar-se falsa'}, {'question': 'Qual item corresponde ao conceito principal de while?', 'options': ['Condição de parada', 'i += 1', 'Pode tornar-se falsa', 'Atualizar a variável de controle'], 'correct': 'Condição de parada'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre while?', 'options': ['Atualizar a variável de controle', 'Condição de parada', 'Pode tornar-se falsa', 'i += 1'], 'correct': 'Atualizar a variável de controle'}, {'question': 'Qual afirmação resume corretamente while?', 'options': ['i += 1', 'Pode tornar-se falsa', 'Atualizar a variável de controle', 'Condição de parada'], 'correct': 'i += 1'}]},
    {'slug': 'laços-repeticao-extra-06', 'title': 'Laços de Repetição — Atividade Extra 06', 'description': 'Atividade pronta de nível facil, revisando loop infinito conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de loop infinito, qual alternativa está correta?', 'options': ['Não é atualizada', 'Variável de controle', 'Condição de parada', 'Garantir que o while possa terminar'], 'correct': 'Não é atualizada'}, {'question': 'Qual item corresponde ao conceito principal de loop infinito?', 'options': ['Variável de controle', 'Condição de parada', 'Não é atualizada', 'Garantir que o while possa terminar'], 'correct': 'Variável de controle'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre loop infinito?', 'options': ['Garantir que o while possa terminar', 'Variável de controle', 'Não é atualizada', 'Condição de parada'], 'correct': 'Garantir que o while possa terminar'}, {'question': 'Qual afirmação resume corretamente loop infinito?', 'options': ['Condição de parada', 'Não é atualizada', 'Garantir que o while possa terminar', 'Variável de controle'], 'correct': 'Condição de parada'}]},
    {'slug': 'laços-repeticao-extra-07', 'title': 'Laços de Repetição — Atividade Extra 07', 'description': 'Atividade pronta de nível facil, revisando break conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de break, qual alternativa está correta?', 'options': ['Encerra a repetição', 'Sai do laço', 'continue', 'Pula a iteração atual'], 'correct': 'Encerra a repetição'}, {'question': 'Qual item corresponde ao conceito principal de break?', 'options': ['Sai do laço', 'continue', 'Encerra a repetição', 'Pula a iteração atual'], 'correct': 'Sai do laço'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre break?', 'options': ['Pula a iteração atual', 'Sai do laço', 'Encerra a repetição', 'continue'], 'correct': 'Pula a iteração atual'}, {'question': 'Qual afirmação resume corretamente break?', 'options': ['continue', 'Encerra a repetição', 'Pula a iteração atual', 'Sai do laço'], 'correct': 'continue'}]},
    {'slug': 'laços-repeticao-extra-08', 'title': 'Laços de Repetição — Atividade Extra 08', 'description': 'Atividade pronta de nível facil, revisando continue conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de continue, qual alternativa está correta?', 'options': ['Permite seguir para a próxima iteração', 'Pula a iteração atual', 'break', 'Sai do laço'], 'correct': 'Permite seguir para a próxima iteração'}, {'question': 'Qual item corresponde ao conceito principal de continue?', 'options': ['Pula a iteração atual', 'break', 'Permite seguir para a próxima iteração', 'Sai do laço'], 'correct': 'Pula a iteração atual'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre continue?', 'options': ['Sai do laço', 'Pula a iteração atual', 'Permite seguir para a próxima iteração', 'break'], 'correct': 'Sai do laço'}, {'question': 'Qual afirmação resume corretamente continue?', 'options': ['break', 'Permite seguir para a próxima iteração', 'Sai do laço', 'Pula a iteração atual'], 'correct': 'break'}]},
    {'slug': 'laços-repeticao-extra-09', 'title': 'Laços de Repetição — Atividade Extra 09', 'description': 'Atividade pronta de nível facil, revisando for x while conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de for x while, qual alternativa está correta?', 'options': ['Sequências conhecidas', 'FOR', 'WHILE', 'Condições dinâmicas'], 'correct': 'Sequências conhecidas'}, {'question': 'Qual item corresponde ao conceito principal de for x while?', 'options': ['FOR', 'WHILE', 'Sequências conhecidas', 'Condições dinâmicas'], 'correct': 'FOR'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre for x while?', 'options': ['Condições dinâmicas', 'FOR', 'Sequências conhecidas', 'WHILE'], 'correct': 'Condições dinâmicas'}, {'question': 'Qual afirmação resume corretamente for x while?', 'options': ['WHILE', 'Sequências conhecidas', 'Condições dinâmicas', 'FOR'], 'correct': 'WHILE'}]},
    {'slug': 'laços-repeticao-extra-10', 'title': 'Laços de Repetição — Atividade Extra 10', 'description': 'Atividade pronta de nível facil, revisando exercício de pares conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de exercício de pares, qual alternativa está correta?', 'options': ['0, 2, 4, 6, 8, 10', 'range(0, 11, 2)', 'n += 2', 'Manter o passo de 2'], 'correct': '0, 2, 4, 6, 8, 10'}, {'question': 'Qual item corresponde ao conceito principal de exercício de pares?', 'options': ['range(0, 11, 2)', 'n += 2', '0, 2, 4, 6, 8, 10', 'Manter o passo de 2'], 'correct': 'range(0, 11, 2)'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre exercício de pares?', 'options': ['Manter o passo de 2', 'range(0, 11, 2)', '0, 2, 4, 6, 8, 10', 'n += 2'], 'correct': 'Manter o passo de 2'}, {'question': 'Qual afirmação resume corretamente exercício de pares?', 'options': ['n += 2', '0, 2, 4, 6, 8, 10', 'Manter o passo de 2', 'range(0, 11, 2)'], 'correct': 'n += 2'}]},
    {'slug': 'laços-repeticao-extra-11', 'title': 'Laços de Repetição — Atividade Extra 11', 'description': 'Atividade pronta de nível facil, revisando desafio do acumulador conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de desafio do acumulador, qual alternativa está correta?', 'options': ['Guardar a soma acumulada', 'total', 'laço de repetição', 'Percorrer valores de 1 a 100'], 'correct': 'Guardar a soma acumulada'}, {'question': 'Qual item corresponde ao conceito principal de desafio do acumulador?', 'options': ['total', 'laço de repetição', 'Guardar a soma acumulada', 'Percorrer valores de 1 a 100'], 'correct': 'total'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre desafio do acumulador?', 'options': ['Percorrer valores de 1 a 100', 'total', 'Guardar a soma acumulada', 'laço de repetição'], 'correct': 'Percorrer valores de 1 a 100'}, {'question': 'Qual afirmação resume corretamente desafio do acumulador?', 'options': ['laço de repetição', 'Guardar a soma acumulada', 'Percorrer valores de 1 a 100', 'total'], 'correct': 'laço de repetição'}]},
    {'slug': 'laços-repeticao-extra-12', 'title': 'Laços de Repetição — Atividade Extra 12', 'description': 'Atividade pronta de nível facil, revisando sintaxe conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de sintaxe, qual alternativa está correta?', 'options': ['Forma correta do for', 'for variável in sequência:', 'while condição:', 'Forma correta do while'], 'correct': 'Forma correta do for'}, {'question': 'Qual item corresponde ao conceito principal de sintaxe?', 'options': ['for variável in sequência:', 'while condição:', 'Forma correta do for', 'Forma correta do while'], 'correct': 'for variável in sequência:'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre sintaxe?', 'options': ['Forma correta do while', 'for variável in sequência:', 'Forma correta do for', 'while condição:'], 'correct': 'Forma correta do while'}, {'question': 'Qual afirmação resume corretamente sintaxe?', 'options': ['while condição:', 'Forma correta do for', 'Forma correta do while', 'for variável in sequência:'], 'correct': 'while condição:'}]},
    {'slug': 'laços-repeticao-extra-13', 'title': 'Laços de Repetição — Atividade Extra 13', 'description': 'Atividade pronta de nível facil, revisando saída do for conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de saída do for, qual alternativa está correta?', 'options': ['Saída de range(3)', '0, 1, 2', '0, 1, 2, 3', 'Não inclui o limite 3'], 'correct': 'Saída de range(3)'}, {'question': 'Qual item corresponde ao conceito principal de saída do for?', 'options': ['0, 1, 2', '0, 1, 2, 3', 'Saída de range(3)', 'Não inclui o limite 3'], 'correct': '0, 1, 2'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre saída do for?', 'options': ['Não inclui o limite 3', '0, 1, 2', 'Saída de range(3)', '0, 1, 2, 3'], 'correct': 'Não inclui o limite 3'}, {'question': 'Qual afirmação resume corretamente saída do for?', 'options': ['0, 1, 2, 3', 'Saída de range(3)', 'Não inclui o limite 3', '0, 1, 2'], 'correct': '0, 1, 2, 3'}]},
    {'slug': 'laços-repeticao-extra-14', 'title': 'Laços de Repetição — Atividade Extra 14', 'description': 'Atividade pronta de nível facil, revisando saída do while conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de saída do while, qual alternativa está correta?', 'options': ['Com i iniciando em 0 e i += 1', '0, 1, 2', '3', 'A condição i < 3 fica falsa em 3'], 'correct': 'Com i iniciando em 0 e i += 1'}, {'question': 'Qual item corresponde ao conceito principal de saída do while?', 'options': ['0, 1, 2', '3', 'Com i iniciando em 0 e i += 1', 'A condição i < 3 fica falsa em 3'], 'correct': '0, 1, 2'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre saída do while?', 'options': ['A condição i < 3 fica falsa em 3', '0, 1, 2', 'Com i iniciando em 0 e i += 1', '3'], 'correct': 'A condição i < 3 fica falsa em 3'}, {'question': 'Qual afirmação resume corretamente saída do while?', 'options': ['3', 'Com i iniciando em 0 e i += 1', 'A condição i < 3 fica falsa em 3', '0, 1, 2'], 'correct': '3'}]},
    {'slug': 'laços-repeticao-extra-15', 'title': 'Laços de Repetição — Atividade Extra 15', 'description': 'Atividade pronta de nível facil, revisando erros comuns conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de erros comuns, qual alternativa está correta?', 'options': ['Obrigatória para o bloco', 'Indentação', 'Loop infinito', 'Pode ocorrer quando a variável não muda'], 'correct': 'Obrigatória para o bloco'}, {'question': 'Qual item corresponde ao conceito principal de erros comuns?', 'options': ['Indentação', 'Loop infinito', 'Obrigatória para o bloco', 'Pode ocorrer quando a variável não muda'], 'correct': 'Indentação'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre erros comuns?', 'options': ['Pode ocorrer quando a variável não muda', 'Indentação', 'Obrigatória para o bloco', 'Loop infinito'], 'correct': 'Pode ocorrer quando a variável não muda'}, {'question': 'Qual afirmação resume corretamente erros comuns?', 'options': ['Loop infinito', 'Obrigatória para o bloco', 'Pode ocorrer quando a variável não muda', 'Indentação'], 'correct': 'Loop infinito'}]},
    {'slug': 'laços-repeticao-extra-16', 'title': 'Laços de Repetição — Atividade Extra 16', 'description': 'Atividade pronta de nível facil, revisando controle de fluxo conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de controle de fluxo, qual alternativa está correta?', 'options': ['Sai do laço', 'break', 'continue', 'Pula uma iteração'], 'correct': 'Sai do laço'}, {'question': 'Qual item corresponde ao conceito principal de controle de fluxo?', 'options': ['break', 'continue', 'Sai do laço', 'Pula uma iteração'], 'correct': 'break'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre controle de fluxo?', 'options': ['Pula uma iteração', 'break', 'Sai do laço', 'continue'], 'correct': 'Pula uma iteração'}, {'question': 'Qual afirmação resume corretamente controle de fluxo?', 'options': ['continue', 'Sai do laço', 'Pula uma iteração', 'break'], 'correct': 'continue'}]},
    {'slug': 'laços-repeticao-extra-17', 'title': 'Laços de Repetição — Atividade Extra 17', 'description': 'Atividade pronta de nível facil, revisando revisão geral conforme o módulo de Laços de Repetição.', 'difficulty': 'facil', 'questions': [{'question': 'Na revisão de revisão geral, qual alternativa está correta?', 'options': ['Tipos de laço trabalhados', 'for e while', 'if e else', 'Estruturas condicionais, não os laços do módulo'], 'correct': 'Tipos de laço trabalhados'}, {'question': 'Qual item corresponde ao conceito principal de revisão geral?', 'options': ['for e while', 'if e else', 'Tipos de laço trabalhados', 'Estruturas condicionais, não os laços do módulo'], 'correct': 'for e while'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre revisão geral?', 'options': ['Estruturas condicionais, não os laços do módulo', 'for e while', 'Tipos de laço trabalhados', 'if e else'], 'correct': 'Estruturas condicionais, não os laços do módulo'}, {'question': 'Qual afirmação resume corretamente revisão geral?', 'options': ['if e else', 'Tipos de laço trabalhados', 'Estruturas condicionais, não os laços do módulo', 'for e while'], 'correct': 'if e else'}]},
    {'slug': 'laços-repeticao-extra-18', 'title': 'Laços de Repetição — Atividade Extra 18', 'description': 'Atividade pronta de nível medio, revisando conceito de laço conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de conceito de laço, qual alternativa está correta?', 'options': ['Executa um bloco várias vezes sem reescrever o código', 'Repetição de um bloco de código', 'Evitar repetição manual de código', 'for e while'], 'correct': 'Executa um bloco várias vezes sem reescrever o código'}, {'question': 'Qual item corresponde ao conceito principal de conceito de laço?', 'options': ['Repetição de um bloco de código', 'Evitar repetição manual de código', 'Executa um bloco várias vezes sem reescrever o código', 'for e while'], 'correct': 'Repetição de um bloco de código'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre conceito de laço?', 'options': ['for e while', 'Repetição de um bloco de código', 'Executa um bloco várias vezes sem reescrever o código', 'Evitar repetição manual de código'], 'correct': 'for e while'}, {'question': 'Qual afirmação resume corretamente conceito de laço?', 'options': ['Evitar repetição manual de código', 'Executa um bloco várias vezes sem reescrever o código', 'for e while', 'Repetição de um bloco de código'], 'correct': 'Evitar repetição manual de código'}]},
    {'slug': 'laços-repeticao-extra-19', 'title': 'Laços de Repetição — Atividade Extra 19', 'description': 'Atividade pronta de nível medio, revisando conceito de laço conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de conceito de laço, qual alternativa está correta?', 'options': ['Percorrer sequências como listas, strings e range()', 'for', 'while', 'Quando uma condição determina o fim'], 'correct': 'Percorrer sequências como listas, strings e range()'}, {'question': 'Qual item corresponde ao conceito principal de conceito de laço?', 'options': ['for', 'while', 'Percorrer sequências como listas, strings e range()', 'Quando uma condição determina o fim'], 'correct': 'for'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre conceito de laço?', 'options': ['Quando uma condição determina o fim', 'for', 'Percorrer sequências como listas, strings e range()', 'while'], 'correct': 'Quando uma condição determina o fim'}, {'question': 'Qual afirmação resume corretamente conceito de laço?', 'options': ['while', 'Percorrer sequências como listas, strings e range()', 'Quando uma condição determina o fim', 'for'], 'correct': 'while'}]},
    {'slug': 'laços-repeticao-extra-20', 'title': 'Laços de Repetição — Atividade Extra 20', 'description': 'Atividade pronta de nível medio, revisando for e range conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de for e range, qual alternativa está correta?', 'options': ['0, 1, 2', 'range(3)', 'range(0, 11, 2)', 'Usar 2 como passo'], 'correct': '0, 1, 2'}, {'question': 'Qual item corresponde ao conceito principal de for e range?', 'options': ['range(3)', 'range(0, 11, 2)', '0, 1, 2', 'Usar 2 como passo'], 'correct': 'range(3)'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre for e range?', 'options': ['Usar 2 como passo', 'range(3)', '0, 1, 2', 'range(0, 11, 2)'], 'correct': 'Usar 2 como passo'}, {'question': 'Qual afirmação resume corretamente for e range?', 'options': ['range(0, 11, 2)', '0, 1, 2', 'Usar 2 como passo', 'range(3)'], 'correct': 'range(0, 11, 2)'}]},
    {'slug': 'laços-repeticao-extra-21', 'title': 'Laços de Repetição — Atividade Extra 21', 'description': 'Atividade pronta de nível medio, revisando for e indentação conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de for e indentação, qual alternativa está correta?', 'options': ['Define o bloco do laço', 'Indentação', 'IndentationError', 'Falta de recuo no bloco'], 'correct': 'Define o bloco do laço'}, {'question': 'Qual item corresponde ao conceito principal de for e indentação?', 'options': ['Indentação', 'IndentationError', 'Define o bloco do laço', 'Falta de recuo no bloco'], 'correct': 'Indentação'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre for e indentação?', 'options': ['Falta de recuo no bloco', 'Indentação', 'Define o bloco do laço', 'IndentationError'], 'correct': 'Falta de recuo no bloco'}, {'question': 'Qual afirmação resume corretamente for e indentação?', 'options': ['IndentationError', 'Define o bloco do laço', 'Falta de recuo no bloco', 'Indentação'], 'correct': 'IndentationError'}]},
    {'slug': 'laços-repeticao-extra-22', 'title': 'Laços de Repetição — Atividade Extra 22', 'description': 'Atividade pronta de nível medio, revisando while conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de while, qual alternativa está correta?', 'options': ['Pode tornar-se falsa', 'Condição de parada', 'i += 1', 'Atualizar a variável de controle'], 'correct': 'Pode tornar-se falsa'}, {'question': 'Qual item corresponde ao conceito principal de while?', 'options': ['Condição de parada', 'i += 1', 'Pode tornar-se falsa', 'Atualizar a variável de controle'], 'correct': 'Condição de parada'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre while?', 'options': ['Atualizar a variável de controle', 'Condição de parada', 'Pode tornar-se falsa', 'i += 1'], 'correct': 'Atualizar a variável de controle'}, {'question': 'Qual afirmação resume corretamente while?', 'options': ['i += 1', 'Pode tornar-se falsa', 'Atualizar a variável de controle', 'Condição de parada'], 'correct': 'i += 1'}]},
    {'slug': 'laços-repeticao-extra-23', 'title': 'Laços de Repetição — Atividade Extra 23', 'description': 'Atividade pronta de nível medio, revisando loop infinito conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de loop infinito, qual alternativa está correta?', 'options': ['Não é atualizada', 'Variável de controle', 'Condição de parada', 'Garantir que o while possa terminar'], 'correct': 'Não é atualizada'}, {'question': 'Qual item corresponde ao conceito principal de loop infinito?', 'options': ['Variável de controle', 'Condição de parada', 'Não é atualizada', 'Garantir que o while possa terminar'], 'correct': 'Variável de controle'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre loop infinito?', 'options': ['Garantir que o while possa terminar', 'Variável de controle', 'Não é atualizada', 'Condição de parada'], 'correct': 'Garantir que o while possa terminar'}, {'question': 'Qual afirmação resume corretamente loop infinito?', 'options': ['Condição de parada', 'Não é atualizada', 'Garantir que o while possa terminar', 'Variável de controle'], 'correct': 'Condição de parada'}]},
    {'slug': 'laços-repeticao-extra-24', 'title': 'Laços de Repetição — Atividade Extra 24', 'description': 'Atividade pronta de nível medio, revisando break conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de break, qual alternativa está correta?', 'options': ['Encerra a repetição', 'Sai do laço', 'continue', 'Pula a iteração atual'], 'correct': 'Encerra a repetição'}, {'question': 'Qual item corresponde ao conceito principal de break?', 'options': ['Sai do laço', 'continue', 'Encerra a repetição', 'Pula a iteração atual'], 'correct': 'Sai do laço'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre break?', 'options': ['Pula a iteração atual', 'Sai do laço', 'Encerra a repetição', 'continue'], 'correct': 'Pula a iteração atual'}, {'question': 'Qual afirmação resume corretamente break?', 'options': ['continue', 'Encerra a repetição', 'Pula a iteração atual', 'Sai do laço'], 'correct': 'continue'}]},
    {'slug': 'laços-repeticao-extra-25', 'title': 'Laços de Repetição — Atividade Extra 25', 'description': 'Atividade pronta de nível medio, revisando continue conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de continue, qual alternativa está correta?', 'options': ['Permite seguir para a próxima iteração', 'Pula a iteração atual', 'break', 'Sai do laço'], 'correct': 'Permite seguir para a próxima iteração'}, {'question': 'Qual item corresponde ao conceito principal de continue?', 'options': ['Pula a iteração atual', 'break', 'Permite seguir para a próxima iteração', 'Sai do laço'], 'correct': 'Pula a iteração atual'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre continue?', 'options': ['Sai do laço', 'Pula a iteração atual', 'Permite seguir para a próxima iteração', 'break'], 'correct': 'Sai do laço'}, {'question': 'Qual afirmação resume corretamente continue?', 'options': ['break', 'Permite seguir para a próxima iteração', 'Sai do laço', 'Pula a iteração atual'], 'correct': 'break'}]},
    {'slug': 'laços-repeticao-extra-26', 'title': 'Laços de Repetição — Atividade Extra 26', 'description': 'Atividade pronta de nível medio, revisando for x while conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de for x while, qual alternativa está correta?', 'options': ['Sequências conhecidas', 'FOR', 'WHILE', 'Condições dinâmicas'], 'correct': 'Sequências conhecidas'}, {'question': 'Qual item corresponde ao conceito principal de for x while?', 'options': ['FOR', 'WHILE', 'Sequências conhecidas', 'Condições dinâmicas'], 'correct': 'FOR'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre for x while?', 'options': ['Condições dinâmicas', 'FOR', 'Sequências conhecidas', 'WHILE'], 'correct': 'Condições dinâmicas'}, {'question': 'Qual afirmação resume corretamente for x while?', 'options': ['WHILE', 'Sequências conhecidas', 'Condições dinâmicas', 'FOR'], 'correct': 'WHILE'}]},
    {'slug': 'laços-repeticao-extra-27', 'title': 'Laços de Repetição — Atividade Extra 27', 'description': 'Atividade pronta de nível medio, revisando exercício de pares conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de exercício de pares, qual alternativa está correta?', 'options': ['0, 2, 4, 6, 8, 10', 'range(0, 11, 2)', 'n += 2', 'Manter o passo de 2'], 'correct': '0, 2, 4, 6, 8, 10'}, {'question': 'Qual item corresponde ao conceito principal de exercício de pares?', 'options': ['range(0, 11, 2)', 'n += 2', '0, 2, 4, 6, 8, 10', 'Manter o passo de 2'], 'correct': 'range(0, 11, 2)'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre exercício de pares?', 'options': ['Manter o passo de 2', 'range(0, 11, 2)', '0, 2, 4, 6, 8, 10', 'n += 2'], 'correct': 'Manter o passo de 2'}, {'question': 'Qual afirmação resume corretamente exercício de pares?', 'options': ['n += 2', '0, 2, 4, 6, 8, 10', 'Manter o passo de 2', 'range(0, 11, 2)'], 'correct': 'n += 2'}]},
    {'slug': 'laços-repeticao-extra-28', 'title': 'Laços de Repetição — Atividade Extra 28', 'description': 'Atividade pronta de nível medio, revisando desafio do acumulador conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de desafio do acumulador, qual alternativa está correta?', 'options': ['Guardar a soma acumulada', 'total', 'laço de repetição', 'Percorrer valores de 1 a 100'], 'correct': 'Guardar a soma acumulada'}, {'question': 'Qual item corresponde ao conceito principal de desafio do acumulador?', 'options': ['total', 'laço de repetição', 'Guardar a soma acumulada', 'Percorrer valores de 1 a 100'], 'correct': 'total'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre desafio do acumulador?', 'options': ['Percorrer valores de 1 a 100', 'total', 'Guardar a soma acumulada', 'laço de repetição'], 'correct': 'Percorrer valores de 1 a 100'}, {'question': 'Qual afirmação resume corretamente desafio do acumulador?', 'options': ['laço de repetição', 'Guardar a soma acumulada', 'Percorrer valores de 1 a 100', 'total'], 'correct': 'laço de repetição'}]},
    {'slug': 'laços-repeticao-extra-29', 'title': 'Laços de Repetição — Atividade Extra 29', 'description': 'Atividade pronta de nível medio, revisando sintaxe conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de sintaxe, qual alternativa está correta?', 'options': ['Forma correta do for', 'for variável in sequência:', 'while condição:', 'Forma correta do while'], 'correct': 'Forma correta do for'}, {'question': 'Qual item corresponde ao conceito principal de sintaxe?', 'options': ['for variável in sequência:', 'while condição:', 'Forma correta do for', 'Forma correta do while'], 'correct': 'for variável in sequência:'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre sintaxe?', 'options': ['Forma correta do while', 'for variável in sequência:', 'Forma correta do for', 'while condição:'], 'correct': 'Forma correta do while'}, {'question': 'Qual afirmação resume corretamente sintaxe?', 'options': ['while condição:', 'Forma correta do for', 'Forma correta do while', 'for variável in sequência:'], 'correct': 'while condição:'}]},
    {'slug': 'laços-repeticao-extra-30', 'title': 'Laços de Repetição — Atividade Extra 30', 'description': 'Atividade pronta de nível medio, revisando saída do for conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de saída do for, qual alternativa está correta?', 'options': ['Saída de range(3)', '0, 1, 2', '0, 1, 2, 3', 'Não inclui o limite 3'], 'correct': 'Saída de range(3)'}, {'question': 'Qual item corresponde ao conceito principal de saída do for?', 'options': ['0, 1, 2', '0, 1, 2, 3', 'Saída de range(3)', 'Não inclui o limite 3'], 'correct': '0, 1, 2'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre saída do for?', 'options': ['Não inclui o limite 3', '0, 1, 2', 'Saída de range(3)', '0, 1, 2, 3'], 'correct': 'Não inclui o limite 3'}, {'question': 'Qual afirmação resume corretamente saída do for?', 'options': ['0, 1, 2, 3', 'Saída de range(3)', 'Não inclui o limite 3', '0, 1, 2'], 'correct': '0, 1, 2, 3'}]},
    {'slug': 'laços-repeticao-extra-31', 'title': 'Laços de Repetição — Atividade Extra 31', 'description': 'Atividade pronta de nível medio, revisando saída do while conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de saída do while, qual alternativa está correta?', 'options': ['Com i iniciando em 0 e i += 1', '0, 1, 2', '3', 'A condição i < 3 fica falsa em 3'], 'correct': 'Com i iniciando em 0 e i += 1'}, {'question': 'Qual item corresponde ao conceito principal de saída do while?', 'options': ['0, 1, 2', '3', 'Com i iniciando em 0 e i += 1', 'A condição i < 3 fica falsa em 3'], 'correct': '0, 1, 2'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre saída do while?', 'options': ['A condição i < 3 fica falsa em 3', '0, 1, 2', 'Com i iniciando em 0 e i += 1', '3'], 'correct': 'A condição i < 3 fica falsa em 3'}, {'question': 'Qual afirmação resume corretamente saída do while?', 'options': ['3', 'Com i iniciando em 0 e i += 1', 'A condição i < 3 fica falsa em 3', '0, 1, 2'], 'correct': '3'}]},
    {'slug': 'laços-repeticao-extra-32', 'title': 'Laços de Repetição — Atividade Extra 32', 'description': 'Atividade pronta de nível medio, revisando erros comuns conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de erros comuns, qual alternativa está correta?', 'options': ['Obrigatória para o bloco', 'Indentação', 'Loop infinito', 'Pode ocorrer quando a variável não muda'], 'correct': 'Obrigatória para o bloco'}, {'question': 'Qual item corresponde ao conceito principal de erros comuns?', 'options': ['Indentação', 'Loop infinito', 'Obrigatória para o bloco', 'Pode ocorrer quando a variável não muda'], 'correct': 'Indentação'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre erros comuns?', 'options': ['Pode ocorrer quando a variável não muda', 'Indentação', 'Obrigatória para o bloco', 'Loop infinito'], 'correct': 'Pode ocorrer quando a variável não muda'}, {'question': 'Qual afirmação resume corretamente erros comuns?', 'options': ['Loop infinito', 'Obrigatória para o bloco', 'Pode ocorrer quando a variável não muda', 'Indentação'], 'correct': 'Loop infinito'}]},
    {'slug': 'laços-repeticao-extra-33', 'title': 'Laços de Repetição — Atividade Extra 33', 'description': 'Atividade pronta de nível medio, revisando controle de fluxo conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de controle de fluxo, qual alternativa está correta?', 'options': ['Sai do laço', 'break', 'continue', 'Pula uma iteração'], 'correct': 'Sai do laço'}, {'question': 'Qual item corresponde ao conceito principal de controle de fluxo?', 'options': ['break', 'continue', 'Sai do laço', 'Pula uma iteração'], 'correct': 'break'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre controle de fluxo?', 'options': ['Pula uma iteração', 'break', 'Sai do laço', 'continue'], 'correct': 'Pula uma iteração'}, {'question': 'Qual afirmação resume corretamente controle de fluxo?', 'options': ['continue', 'Sai do laço', 'Pula uma iteração', 'break'], 'correct': 'continue'}]},
    {'slug': 'laços-repeticao-extra-34', 'title': 'Laços de Repetição — Atividade Extra 34', 'description': 'Atividade pronta de nível medio, revisando revisão geral conforme o módulo de Laços de Repetição.', 'difficulty': 'medio', 'questions': [{'question': 'Na revisão de revisão geral, qual alternativa está correta?', 'options': ['Tipos de laço trabalhados', 'for e while', 'if e else', 'Estruturas condicionais, não os laços do módulo'], 'correct': 'Tipos de laço trabalhados'}, {'question': 'Qual item corresponde ao conceito principal de revisão geral?', 'options': ['for e while', 'if e else', 'Tipos de laço trabalhados', 'Estruturas condicionais, não os laços do módulo'], 'correct': 'for e while'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre revisão geral?', 'options': ['Estruturas condicionais, não os laços do módulo', 'for e while', 'Tipos de laço trabalhados', 'if e else'], 'correct': 'Estruturas condicionais, não os laços do módulo'}, {'question': 'Qual afirmação resume corretamente revisão geral?', 'options': ['if e else', 'Tipos de laço trabalhados', 'Estruturas condicionais, não os laços do módulo', 'for e while'], 'correct': 'if e else'}]},
    {'slug': 'laços-repeticao-extra-35', 'title': 'Laços de Repetição — Atividade Extra 35', 'description': 'Atividade pronta de nível dificil, revisando conceito de laço conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de conceito de laço, qual alternativa está correta?', 'options': ['Executa um bloco várias vezes sem reescrever o código', 'Repetição de um bloco de código', 'Evitar repetição manual de código', 'for e while'], 'correct': 'Executa um bloco várias vezes sem reescrever o código'}, {'question': 'Qual item corresponde ao conceito principal de conceito de laço?', 'options': ['Repetição de um bloco de código', 'Evitar repetição manual de código', 'Executa um bloco várias vezes sem reescrever o código', 'for e while'], 'correct': 'Repetição de um bloco de código'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre conceito de laço?', 'options': ['for e while', 'Repetição de um bloco de código', 'Executa um bloco várias vezes sem reescrever o código', 'Evitar repetição manual de código'], 'correct': 'for e while'}, {'question': 'Qual afirmação resume corretamente conceito de laço?', 'options': ['Evitar repetição manual de código', 'Executa um bloco várias vezes sem reescrever o código', 'for e while', 'Repetição de um bloco de código'], 'correct': 'Evitar repetição manual de código'}]},
    {'slug': 'laços-repeticao-extra-36', 'title': 'Laços de Repetição — Atividade Extra 36', 'description': 'Atividade pronta de nível dificil, revisando conceito de laço conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de conceito de laço, qual alternativa está correta?', 'options': ['Percorrer sequências como listas, strings e range()', 'for', 'while', 'Quando uma condição determina o fim'], 'correct': 'Percorrer sequências como listas, strings e range()'}, {'question': 'Qual item corresponde ao conceito principal de conceito de laço?', 'options': ['for', 'while', 'Percorrer sequências como listas, strings e range()', 'Quando uma condição determina o fim'], 'correct': 'for'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre conceito de laço?', 'options': ['Quando uma condição determina o fim', 'for', 'Percorrer sequências como listas, strings e range()', 'while'], 'correct': 'Quando uma condição determina o fim'}, {'question': 'Qual afirmação resume corretamente conceito de laço?', 'options': ['while', 'Percorrer sequências como listas, strings e range()', 'Quando uma condição determina o fim', 'for'], 'correct': 'while'}]},
    {'slug': 'laços-repeticao-extra-37', 'title': 'Laços de Repetição — Atividade Extra 37', 'description': 'Atividade pronta de nível dificil, revisando for e range conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de for e range, qual alternativa está correta?', 'options': ['0, 1, 2', 'range(3)', 'range(0, 11, 2)', 'Usar 2 como passo'], 'correct': '0, 1, 2'}, {'question': 'Qual item corresponde ao conceito principal de for e range?', 'options': ['range(3)', 'range(0, 11, 2)', '0, 1, 2', 'Usar 2 como passo'], 'correct': 'range(3)'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre for e range?', 'options': ['Usar 2 como passo', 'range(3)', '0, 1, 2', 'range(0, 11, 2)'], 'correct': 'Usar 2 como passo'}, {'question': 'Qual afirmação resume corretamente for e range?', 'options': ['range(0, 11, 2)', '0, 1, 2', 'Usar 2 como passo', 'range(3)'], 'correct': 'range(0, 11, 2)'}]},
    {'slug': 'laços-repeticao-extra-38', 'title': 'Laços de Repetição — Atividade Extra 38', 'description': 'Atividade pronta de nível dificil, revisando for e indentação conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de for e indentação, qual alternativa está correta?', 'options': ['Define o bloco do laço', 'Indentação', 'IndentationError', 'Falta de recuo no bloco'], 'correct': 'Define o bloco do laço'}, {'question': 'Qual item corresponde ao conceito principal de for e indentação?', 'options': ['Indentação', 'IndentationError', 'Define o bloco do laço', 'Falta de recuo no bloco'], 'correct': 'Indentação'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre for e indentação?', 'options': ['Falta de recuo no bloco', 'Indentação', 'Define o bloco do laço', 'IndentationError'], 'correct': 'Falta de recuo no bloco'}, {'question': 'Qual afirmação resume corretamente for e indentação?', 'options': ['IndentationError', 'Define o bloco do laço', 'Falta de recuo no bloco', 'Indentação'], 'correct': 'IndentationError'}]},
    {'slug': 'laços-repeticao-extra-39', 'title': 'Laços de Repetição — Atividade Extra 39', 'description': 'Atividade pronta de nível dificil, revisando while conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de while, qual alternativa está correta?', 'options': ['Pode tornar-se falsa', 'Condição de parada', 'i += 1', 'Atualizar a variável de controle'], 'correct': 'Pode tornar-se falsa'}, {'question': 'Qual item corresponde ao conceito principal de while?', 'options': ['Condição de parada', 'i += 1', 'Pode tornar-se falsa', 'Atualizar a variável de controle'], 'correct': 'Condição de parada'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre while?', 'options': ['Atualizar a variável de controle', 'Condição de parada', 'Pode tornar-se falsa', 'i += 1'], 'correct': 'Atualizar a variável de controle'}, {'question': 'Qual afirmação resume corretamente while?', 'options': ['i += 1', 'Pode tornar-se falsa', 'Atualizar a variável de controle', 'Condição de parada'], 'correct': 'i += 1'}]},
    {'slug': 'laços-repeticao-extra-40', 'title': 'Laços de Repetição — Atividade Extra 40', 'description': 'Atividade pronta de nível dificil, revisando loop infinito conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de loop infinito, qual alternativa está correta?', 'options': ['Não é atualizada', 'Variável de controle', 'Condição de parada', 'Garantir que o while possa terminar'], 'correct': 'Não é atualizada'}, {'question': 'Qual item corresponde ao conceito principal de loop infinito?', 'options': ['Variável de controle', 'Condição de parada', 'Não é atualizada', 'Garantir que o while possa terminar'], 'correct': 'Variável de controle'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre loop infinito?', 'options': ['Garantir que o while possa terminar', 'Variável de controle', 'Não é atualizada', 'Condição de parada'], 'correct': 'Garantir que o while possa terminar'}, {'question': 'Qual afirmação resume corretamente loop infinito?', 'options': ['Condição de parada', 'Não é atualizada', 'Garantir que o while possa terminar', 'Variável de controle'], 'correct': 'Condição de parada'}]},
    {'slug': 'laços-repeticao-extra-41', 'title': 'Laços de Repetição — Atividade Extra 41', 'description': 'Atividade pronta de nível dificil, revisando break conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de break, qual alternativa está correta?', 'options': ['Encerra a repetição', 'Sai do laço', 'continue', 'Pula a iteração atual'], 'correct': 'Encerra a repetição'}, {'question': 'Qual item corresponde ao conceito principal de break?', 'options': ['Sai do laço', 'continue', 'Encerra a repetição', 'Pula a iteração atual'], 'correct': 'Sai do laço'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre break?', 'options': ['Pula a iteração atual', 'Sai do laço', 'Encerra a repetição', 'continue'], 'correct': 'Pula a iteração atual'}, {'question': 'Qual afirmação resume corretamente break?', 'options': ['continue', 'Encerra a repetição', 'Pula a iteração atual', 'Sai do laço'], 'correct': 'continue'}]},
    {'slug': 'laços-repeticao-extra-42', 'title': 'Laços de Repetição — Atividade Extra 42', 'description': 'Atividade pronta de nível dificil, revisando continue conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de continue, qual alternativa está correta?', 'options': ['Permite seguir para a próxima iteração', 'Pula a iteração atual', 'break', 'Sai do laço'], 'correct': 'Permite seguir para a próxima iteração'}, {'question': 'Qual item corresponde ao conceito principal de continue?', 'options': ['Pula a iteração atual', 'break', 'Permite seguir para a próxima iteração', 'Sai do laço'], 'correct': 'Pula a iteração atual'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre continue?', 'options': ['Sai do laço', 'Pula a iteração atual', 'Permite seguir para a próxima iteração', 'break'], 'correct': 'Sai do laço'}, {'question': 'Qual afirmação resume corretamente continue?', 'options': ['break', 'Permite seguir para a próxima iteração', 'Sai do laço', 'Pula a iteração atual'], 'correct': 'break'}]},
    {'slug': 'laços-repeticao-extra-43', 'title': 'Laços de Repetição — Atividade Extra 43', 'description': 'Atividade pronta de nível dificil, revisando for x while conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de for x while, qual alternativa está correta?', 'options': ['Sequências conhecidas', 'FOR', 'WHILE', 'Condições dinâmicas'], 'correct': 'Sequências conhecidas'}, {'question': 'Qual item corresponde ao conceito principal de for x while?', 'options': ['FOR', 'WHILE', 'Sequências conhecidas', 'Condições dinâmicas'], 'correct': 'FOR'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre for x while?', 'options': ['Condições dinâmicas', 'FOR', 'Sequências conhecidas', 'WHILE'], 'correct': 'Condições dinâmicas'}, {'question': 'Qual afirmação resume corretamente for x while?', 'options': ['WHILE', 'Sequências conhecidas', 'Condições dinâmicas', 'FOR'], 'correct': 'WHILE'}]},
    {'slug': 'laços-repeticao-extra-44', 'title': 'Laços de Repetição — Atividade Extra 44', 'description': 'Atividade pronta de nível dificil, revisando exercício de pares conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de exercício de pares, qual alternativa está correta?', 'options': ['0, 2, 4, 6, 8, 10', 'range(0, 11, 2)', 'n += 2', 'Manter o passo de 2'], 'correct': '0, 2, 4, 6, 8, 10'}, {'question': 'Qual item corresponde ao conceito principal de exercício de pares?', 'options': ['range(0, 11, 2)', 'n += 2', '0, 2, 4, 6, 8, 10', 'Manter o passo de 2'], 'correct': 'range(0, 11, 2)'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre exercício de pares?', 'options': ['Manter o passo de 2', 'range(0, 11, 2)', '0, 2, 4, 6, 8, 10', 'n += 2'], 'correct': 'Manter o passo de 2'}, {'question': 'Qual afirmação resume corretamente exercício de pares?', 'options': ['n += 2', '0, 2, 4, 6, 8, 10', 'Manter o passo de 2', 'range(0, 11, 2)'], 'correct': 'n += 2'}]},
    {'slug': 'laços-repeticao-extra-45', 'title': 'Laços de Repetição — Atividade Extra 45', 'description': 'Atividade pronta de nível dificil, revisando desafio do acumulador conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de desafio do acumulador, qual alternativa está correta?', 'options': ['Guardar a soma acumulada', 'total', 'laço de repetição', 'Percorrer valores de 1 a 100'], 'correct': 'Guardar a soma acumulada'}, {'question': 'Qual item corresponde ao conceito principal de desafio do acumulador?', 'options': ['total', 'laço de repetição', 'Guardar a soma acumulada', 'Percorrer valores de 1 a 100'], 'correct': 'total'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre desafio do acumulador?', 'options': ['Percorrer valores de 1 a 100', 'total', 'Guardar a soma acumulada', 'laço de repetição'], 'correct': 'Percorrer valores de 1 a 100'}, {'question': 'Qual afirmação resume corretamente desafio do acumulador?', 'options': ['laço de repetição', 'Guardar a soma acumulada', 'Percorrer valores de 1 a 100', 'total'], 'correct': 'laço de repetição'}]},
    {'slug': 'laços-repeticao-extra-46', 'title': 'Laços de Repetição — Atividade Extra 46', 'description': 'Atividade pronta de nível dificil, revisando sintaxe conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de sintaxe, qual alternativa está correta?', 'options': ['Forma correta do for', 'for variável in sequência:', 'while condição:', 'Forma correta do while'], 'correct': 'Forma correta do for'}, {'question': 'Qual item corresponde ao conceito principal de sintaxe?', 'options': ['for variável in sequência:', 'while condição:', 'Forma correta do for', 'Forma correta do while'], 'correct': 'for variável in sequência:'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre sintaxe?', 'options': ['Forma correta do while', 'for variável in sequência:', 'Forma correta do for', 'while condição:'], 'correct': 'Forma correta do while'}, {'question': 'Qual afirmação resume corretamente sintaxe?', 'options': ['while condição:', 'Forma correta do for', 'Forma correta do while', 'for variável in sequência:'], 'correct': 'while condição:'}]},
    {'slug': 'laços-repeticao-extra-47', 'title': 'Laços de Repetição — Atividade Extra 47', 'description': 'Atividade pronta de nível dificil, revisando saída do for conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de saída do for, qual alternativa está correta?', 'options': ['Saída de range(3)', '0, 1, 2', '0, 1, 2, 3', 'Não inclui o limite 3'], 'correct': 'Saída de range(3)'}, {'question': 'Qual item corresponde ao conceito principal de saída do for?', 'options': ['0, 1, 2', '0, 1, 2, 3', 'Saída de range(3)', 'Não inclui o limite 3'], 'correct': '0, 1, 2'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre saída do for?', 'options': ['Não inclui o limite 3', '0, 1, 2', 'Saída de range(3)', '0, 1, 2, 3'], 'correct': 'Não inclui o limite 3'}, {'question': 'Qual afirmação resume corretamente saída do for?', 'options': ['0, 1, 2, 3', 'Saída de range(3)', 'Não inclui o limite 3', '0, 1, 2'], 'correct': '0, 1, 2, 3'}]},
    {'slug': 'laços-repeticao-extra-48', 'title': 'Laços de Repetição — Atividade Extra 48', 'description': 'Atividade pronta de nível dificil, revisando saída do while conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de saída do while, qual alternativa está correta?', 'options': ['Com i iniciando em 0 e i += 1', '0, 1, 2', '3', 'A condição i < 3 fica falsa em 3'], 'correct': 'Com i iniciando em 0 e i += 1'}, {'question': 'Qual item corresponde ao conceito principal de saída do while?', 'options': ['0, 1, 2', '3', 'Com i iniciando em 0 e i += 1', 'A condição i < 3 fica falsa em 3'], 'correct': '0, 1, 2'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre saída do while?', 'options': ['A condição i < 3 fica falsa em 3', '0, 1, 2', 'Com i iniciando em 0 e i += 1', '3'], 'correct': 'A condição i < 3 fica falsa em 3'}, {'question': 'Qual afirmação resume corretamente saída do while?', 'options': ['3', 'Com i iniciando em 0 e i += 1', 'A condição i < 3 fica falsa em 3', '0, 1, 2'], 'correct': '3'}]},
    {'slug': 'laços-repeticao-extra-49', 'title': 'Laços de Repetição — Atividade Extra 49', 'description': 'Atividade pronta de nível dificil, revisando erros comuns conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de erros comuns, qual alternativa está correta?', 'options': ['Obrigatória para o bloco', 'Indentação', 'Loop infinito', 'Pode ocorrer quando a variável não muda'], 'correct': 'Obrigatória para o bloco'}, {'question': 'Qual item corresponde ao conceito principal de erros comuns?', 'options': ['Indentação', 'Loop infinito', 'Obrigatória para o bloco', 'Pode ocorrer quando a variável não muda'], 'correct': 'Indentação'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre erros comuns?', 'options': ['Pode ocorrer quando a variável não muda', 'Indentação', 'Obrigatória para o bloco', 'Loop infinito'], 'correct': 'Pode ocorrer quando a variável não muda'}, {'question': 'Qual afirmação resume corretamente erros comuns?', 'options': ['Loop infinito', 'Obrigatória para o bloco', 'Pode ocorrer quando a variável não muda', 'Indentação'], 'correct': 'Loop infinito'}]},
    {'slug': 'laços-repeticao-extra-50', 'title': 'Laços de Repetição — Atividade Extra 50', 'description': 'Atividade pronta de nível dificil, revisando controle de fluxo conforme o módulo de Laços de Repetição.', 'difficulty': 'dificil', 'questions': [{'question': 'Na revisão de controle de fluxo, qual alternativa está correta?', 'options': ['Sai do laço', 'break', 'continue', 'Pula uma iteração'], 'correct': 'Sai do laço'}, {'question': 'Qual item corresponde ao conceito principal de controle de fluxo?', 'options': ['break', 'continue', 'Sai do laço', 'Pula uma iteração'], 'correct': 'break'}, {'question': 'Qual alternativa NÃO corresponde ao conteúdo trabalhado sobre controle de fluxo?', 'options': ['Pula uma iteração', 'break', 'Sai do laço', 'continue'], 'correct': 'Pula uma iteração'}, {'question': 'Qual afirmação resume corretamente controle de fluxo?', 'options': ['continue', 'Sai do laço', 'Pula uma iteração', 'break'], 'correct': 'continue'}]},
]

PREBUILT_ACTIVITIES.extend(_ADDITIONAL)

BY_SLUG = {item["slug"]: item for item in PREBUILT_ACTIVITIES}
